### ISSUE TITLE
demo.ctraderapi.com:5035 not supporting ProtoOARefreshTokenReq

### ISSUE THREAD

**Issue by claasahl** [spotware/Open-API-2.0-protobuf-messages#15]
The server `demo.ctraderapi.com:5035` seems to be on version 6.5 (according to `ProtoOAVersionReq`), but doesn't support `ProtoOARefreshTokenReq`s. Is this intentional?

**Comment by LeoSko** [comment]
@claasahl, this message was added to protocol but not yet released to our production backend. We expect it to be released in Q2.
