### ISSUE TITLE
Cannot decode response of ProtoOADealListReq

### ISSUE THREAD

**Issue by keyyuki** [spotware/Open-API-2.0-protobuf-messages#17]
i have try to get historical data from a day that i have more than 5 transaction. 
the request format 
```
{
ctidTraderAccountId: mynumber
fromTimestamp: 
toTimestamp:
}
```

it response can not decode. I use Nodejs, I have tried  `protobufjs `and `google-protobuf` but cannot 

there are response in base64
```
AAAD0QjWEBKpBxDf+OgIGlsIzpyCFhCloPYTGKu3lwsgwIQ9KMCEPTABOOeplYe3LkDoq5WHty5I56mVh7cuUaAVGLK6VfI/WAFgAmkAAAAAAADwP3DT//////////8BeaAVGLK6VfI/iAECGlsIvpyCFhCToPYTGKO3lwsgwIQ9KMCEPTABONXblIe3LkC+3ZSHty5I1duUh7cuUaJFtvP9VPI/WAFgAmkAAAAAAADwP3DT//////////8BeaJFtvP9VPI/iAECGlsIqJyCFhD7n/YTGJ23lwsgwIQ9KMCEPTABOOycj4e3LkD6no+Hty5I7JyPh7cuUfiqlQm/VPI/WAFgAmkAAAAAAADwP3DT//////////8BefiqlQm/VPI/iAECGlsIp5yCFhD6n/YTGJy3lwsgwIQ9KMCEPTABONnOjoe3LkDb0I6Hty5I2c6Oh7cuUfiqlQm/VPI/WAFgAmkAAAAAAADwP3DT//////////8BefiqlQm/VPI/iAECGlsIpZyCFhD3n/YTGJq3lwsgwIQ9KMCEPTABOOuBjoe3LkDyg46Hty5I64GOh7cuUfiqlQm/VPI/WAFgAmkAAAAAAADwP3DT//////////8BeWlv8IXJVPI/iAECGlsIqJqCFhD8nfYTGPC2lwsgwIQ9KMCEPTABOOyE7Ya3LkD5hu2Gty5I7ITthrcuUXK/Q1GgT/I/WAFgAmkAAAAAAADwP3DT//////////8BeR1yM9yAT/I/iAECGlsIp5qCFhD7nfYTGO+2lwsgwIQ9KMCEPTABOJ237Ia3LkCxueyGty5InbfshrcuUZBOXfksT/I/WAFgAmkAAAAAAADwP3DT//////////8BeZBOXfksT/I/iAECGlsIm5SCFhDrl/YTGMy1lwsgwIQ9KMCEPTABOJ6vxoW3LkDxsMaFty5Inq/GhbcuUQgDz72HS/I/WAFgAmkAAAAAAADwP3DT//////////8BeQgDz72HS/I/iAECGlsI/5OCFhDOl/YTGL21lwsgwIQ9KMCEPTABOM7pwoW3LkDW68KFty5IzunChbcuUXZPHhZqTfI/WAFgAmkAAAAAAADwP3DT//////////8BeXZPHhZqTfI/iAECGlsI+5OCFhDHl/YTGLm1lwsgwIQ9KMCEPTABOP7LwYW3LkDIzcGFty5I/svBhbcuUSDSb18HTvI/WAFgAmkAAAAAAADwP3DT//////////8BeSDSb18HTvI/iAECIAAaIGQ5ZmQ3NjhlOTE5MzlkNDYyZTRlNjQ3NzlkMWU0ZmJi
```

But when i try in a day that no transaction, it decode ok. And when I set maxRows = 5, it decode ok. Change maxRows to any number is cannot decode.

**Comment by LeoSko** [comment]
I couldn't decode your response either. Is it a `ProtoMessage` or `ProtoOADealListRes`?
* Try some other request to see if this is decoder's issue (e.g. `ProtoOACashFlowHistoryListReq`)
* In the meanwhile, try decoding this full `ProtoOADealListReq` that is used in my test:

`EAEaTAigVBDUBhjQBiDAmgwowJoMMAE49o/EhLkuQJGQxIS5Lkj2j8SEuS5Rnu+nxks38z9YAWACaZ7vp8ZLN/M/cAB5nu+nxks38z+IAQIaTAifVBDTBhjPBiDAmgwowJoMMAE414/EhLkuQPCPxIS5LkjXj8SEuS5Rnu+nxks38z9YAWACaZ7vp8ZLN/M/cAB5nu+nxks38z+IAQIaTAieVBDSBhjOBiDAmgwowJoMMAE4qI/EhLkuQMaPxIS5Lkioj8SEuS5Rnu+nxks38z9YAWACaZ7vp8ZLN/M/cAB5nu+nxks38z+IAQIaTAidVBDRBhjNBiDAmgwowJoMMAE4/Y7EhLkuQJ2PxIS5Lkj9jsSEuS5Rnu+nxks38z9YAWACaZ7vp8ZLN/M/cAB5nu+nxks38z+IAQIaTAicVBDQBhjMBiDAmgwowJoMMAE41I7EhLkuQPKOxIS5LkjUjsSEuS5Rnu+nxks38z9YAWACaZ7vp8ZLN/M/cAB5nu+nxks38z+IAQIaTAibVBDPBhjLBiCAiXoogIl6MAE4kY7EhLkuQKuOxIS5LkiRjsSEuS5Rnu+nxks38z9YAWACaZ7vp8ZLN/M/cAB5nu+nxks38z+IAQIadwiZVBDNBhjJBiCAkvQBKICS9AEwATi+jcSEuS5A2Y3EhLkuSL6NxIS5LlGe76fGSzfzP1gCYAJpnu+nxks38z9wAHme76fGSzfzP4IBJgme76fGSzfzPxAAGAAgACiAreIEMQAAAAAAAPA/OICS9AFAAkgCiAECGk4ImFQQzAYYyQYggJL0ASiAkvQBMAE4k43EhLkuQLCNxIS5LkiTjcSEuS5Rnu+nxks38z9YAWACaZ7vp8ZLN/M/cAB5nu+nxks38z+IAQIgAA==`

**Comment by keyyuki** [comment]
at last i found reason. 4 first byte is lenght of response and must be remove before decode. Thanks for response https://github.com/claasahl/spotware-adapter
