### ISSUE TITLE
Need add field comment and clientOrderId to deal, position and order response

### ISSUE THREAD

**Issue by keyyuki** [spotware/Open-API-2.0-protobuf-messages#18]
in message create new order `ProtoOANewOrderReq` have field `optional string comment` and `optional string clientOrderId` but model `ProtoOAPosition`, `ProtoOAOrder`, `ProtoOADeal` do not have that fields.

**Comment by LeoSko** [comment]
* `ProtoOAOrder` already contains `clientOrderId`
* There is no point in adding those fields to other entities, since they relate only to order
* We will consider adding `comment`, will let you know on decision

**Comment by LeoSko** [comment]
We are going to add `ProtoOATradeData.comment` in the closest (70) release.
