### ISSUE TITLE
Is "deltaClose" in "ProtoOATrendbar" populated?

### ISSUE THREAD

**Issue by claasahl** [spotware/Open-API-2.0-protobuf-messages#9]
I am referring to this field: https://github.com/spotware/Open-API-2.0-protobuf-messages/blob/master/6.3%20(Current)/OpenApiModelMessages.proto#L485

When subscribing to live trendbars (i.e. https://github.com/spotware/Open-API-2.0-protobuf-messages/blob/master/6.3%20(Current)/OpenApiMessages.proto#L439-L445), trendbars start to trickle in as expected. However, these trendbars appear to be missing the field "deltaClose". All other fields are present.

- (present) required int64 volume = 3; // Bar volume in ticks.
- (present) optional ProtoOATrendbarPeriod period = 4 [default = M1]; // Bar period.
- (present) optional int64 low = 5; // Low price of the bar.
- (present) optional uint64 deltaOpen = 6; // Delta between open and low price. open = low + deltaOpen.
- **(missing) optional uint64 deltaClose = 7; // Delta between open and low price. close = low + deltaClose.**
- (present) optional uint64 deltaHigh = 8; // Delta between open and low price. high = low + deltaHigh.
- (present) optional uint32 utcTimestampInMinutes = 9; // Timestamp of the bar. Equal to the timestamp of the open tick.

Upon inspection of the binary protobuf-messages, I cannot find traces of this field (i.e. field 7 / deltaClose) either. 

Is this intended?

**Comment by LeoSko** [comment]
Hi, @claasahl.
Note that `deltaClose` field appears only in *historical* requests like `ProtoOAGetTrendbarsReq/Res` to indicate closed trendbars. If you subscribe to *live* trendbars via `ProtoOASubscribeLiveTrendbarReq` they don't contain any `deltaClose`.

**Comment by claasahl** [comment]
thanks for your feedback, @LeoSko 

I take it that this behavior is intentional :)
